services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: sortorium-frontend-local
    image: sortorium-frontend-local:latest
    env_file: .env.local
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
