import { all_routes } from "@/data/all_routes";

const route = all_routes;

export const SidebarData = [
  {
    label: "Main",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "Main",
    submenuItems: [
      {
        label: "Dashboard",
        icon: "layout-grid",
        submenu: true,
        showSubRoute: false,
        roles: ["owner", "manager"],
        featureKey: "dashboard",
        submenuItems: [
          { label: "Admin Dashboard", link: "/admin-dashboard", featureKey: "dashboard" },
          { label: "Sales Dashboard", link: "/sales-dashboard", featureKey: "dashboard" },
          { label: "Branch Overview", link: "/dashboard", roles: ["owner"], featureKey: "dashboard" },
        ],
      },
      {
        label: "Overview",
        icon: "user-edit",
        submenu: true,
        showSubRoute: false,
        roles: ["platform"],
        submenuItems: [
          { label: "Dashboard", link: route.vendorDashboard, featureKey: "platform.dashboard" },
          { label: "Companies", link: "/companies", featureKey: "platform.tenants" },
          { label: "Subscriptions", link: "/subscription", featureKey: "platform.subscriptions" },
          { label: "Packages", link: "/packages", featureKey: "platform.packages" },
          { label: "Products", link: "/software-products", featureKey: "platform.products" },
          { label: "Domain", link: "/domain", featureKey: "platform.domain" },
          { label: "Invoices", link: route.purchasetransaction, featureKey: "platform.invoices" },
        ],
      },
      {
        label: "Application",
        icon: "brand-apple-arcade",
        submenu: true,
        showSubRoute: false,
        roles: ["owner", "manager"],
        submenuItems: [
          { label: "Chat", link: "/chat", showSubRoute: false },
          {
            label: "Call",
            submenu: true,
            submenuItems: [
              { label: "Video Call", link: "/video-call" },
              { label: "Audio Call", link: "/audio-call" },
              { label: "Call History", link: "/call-history" },
            ],
          },
          { label: "Calendar", link: "/calendar", showSubRoute: false },
          { label: "Contact", link: "/contacts", showSubRoute: false },
          { label: "Email", link: "/email", showSubRoute: false },
          { label: "To Do", link: "/todo", showSubRoute: false },
          { label: "Notes", link: "/notes", showSubRoute: false },
          { label: "File Manager", link: "/file-manager", showSubRoute: false },
          { label: "Projects", link: "/projects", showSubRoute: false },
          {
            label: "Ecommerce",
            submenu: true,
            submenuItems: [
              { label: "Products", link: "/products" },
              { label: "Orders", link: "/orders" },
              { label: "Customers", link: "/customers" },
              { label: "Cart", link: "/cart" },
              { label: "Checkout", link: "/checkout" },
              { label: "Wishlist", link: "/wishlist" },
              { label: "Reviews", link: "/reviews" },
            ],
          },
          { label: "Social Feed", link: "/social-feed", showSubRoute: false },
          { label: "Search List", link: "/search-list", showSubRoute: false },
        ],
      },
      {
        label: "Layouts",
        icon: "layout-sidebar-right-collapse",
        submenu: true,
        showSubRoute: false,
        roles: ["owner"],
        submenuItems: [
          { label: "Horizontal", link: route.Horizontal, showSubRoute: false },
          { label: "Detached", link: route.Detached, showSubRoute: false },
          { label: "Two Column", link: route.TwoColumn, showSubRoute: false },
          { label: "Hovered", link: route.Hovered, showSubRoute: false },
          { label: "Boxed", link: route.Boxed, showSubRoute: false },
          { label: "RTL", link: route.RTL, showSubRoute: false },
          { label: "Dark", link: route.Dark, showSubRoute: false },
        ],
      },
    ],
  },
  {
    label: "Inventory",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "Inventory",
    roles: ["owner", "manager"],
    submenuItems: [
      {
        label: "Products",
        link: "/product-list",
        icon: "box",
        showSubRoute: false,
        submenu: false,
        featureKey: "products",
      },
      {
        label: "Create Product",
        link: "/add-product",
        icon: "table-plus",
        showSubRoute: false,
        submenu: false,
        featureKey: "add_product",
      },
      {
        label: "Expired Products",
        link: "/expired-products",
        icon: "progress-alert",
        showSubRoute: false,
        submenu: false,
        featureKey: "expired_products",
      },
      {
        label: "Low Stocks",
        link: "/low-stocks",
        icon: "trending-up-2",
        showSubRoute: false,
        submenu: false,
        featureKey: "low_stocks",
      },
      {
        label: "Category",
        link: "/category-list",
        icon: "list-details",
        showSubRoute: false,
        submenu: false,
        featureKey: "categories",
      },
      {
        label: "Sub Category",
        link: "/sub-categories",
        icon: "carousel-vertical",
        showSubRoute: false,
        submenu: false,
        featureKey: "sub_categories",
      },
      {
        label: "Brands",
        link: "/brand-list",
        icon: "triangles",
        showSubRoute: false,
        submenu: false,
        featureKey: "brands",
      },
      {
        label: "Units",
        link: "/units",
        icon: "brand-unity",
        showSubRoute: false,
        submenu: false,
        featureKey: "units",
      },
      {
        label: "Variant Attributes",
        link: "/variant-attributes",
        icon: "checklist",
        showSubRoute: false,
        submenu: false,
        featureKey: "variant_attributes",
      },
      {
        label: "Warranties",
        link: "/warranty",
        icon: "certificate",
        showSubRoute: false,
        submenu: false,
        featureKey: "warranties",
      },
      {
        label: "Print Barcode",
        link: "/barcode",
        icon: "barcode",
        showSubRoute: false,
        submenu: false,
        featureKey: "barcodes",
      },
      {
        label: "Print QR Code",
        link: "/qrcode",
        icon: "qrcode",
        showSubRoute: false,
        submenu: false,
        featureKey: "qrcodes",
      },
    ],
  },
  {
    label: "Stock",
    submenuOpen: true,
    submenuHdr: "Stock",
    submenu: true,
    showSubRoute: false,
    roles: ["owner", "manager"],
    submenuItems: [
      {
        label: "Manage Stock",
        link: "/manage-stocks",
        icon: "stack-3",
        showSubRoute: false,
        submenu: false,
        featureKey: "manage_stocks",
      },
      {
        label: "Stock Adjustment",
        link: "/stock-adjustment",
        icon: "stairs-up",
        showSubRoute: false,
        submenu: false,
        featureKey: "stock_adjustment",
      },
      {
        label: "Stock Transfer",
        link: "/stock-transfer",
        icon: "stack-pop",
        showSubRoute: false,
        submenu: false,
        featureKey: "stock_transfer",
      },
    ],
  },
  {
    label: "Sales",
    submenuOpen: true,
    submenuHdr: "Sales",
    submenu: false,
    showSubRoute: false,
    roles: ["owner", "manager"],
    submenuItems: [
      {
        label: "Sales",
        icon: "layout-grid",
        showSubRoute: false,
        submenu: true,
        submenuItems: [
          {
            label: "Online Orders",
            link: route.onlineorder,
            showSubRoute: false,
            featureKey: "online_orders",
          },
          { label: "POS Orders", link: route.posorder, showSubRoute: false, featureKey: "pos_orders" },
        ],
      },
      {
        label: "Invoices",
        link: route.invoice,
        icon: "file-invoice",
        showSubRoute: false,
        submenu: false,
        featureKey: "invoices",
      },
      {
        label: "Sales Return",
        link: "/sales-returns",
        icon: "receipt-refund",
        showSubRoute: false,
        submenu: false,
        featureKey: "sales_returns",
      },
      {
        label: "Quotation",
        link: "/quotation-list",
        icon: "files",
        showSubRoute: false,
        submenu: false,
        featureKey: "quotations",
      },
      {
        label: "POS",
        icon: "device-laptop",
        showSubRoute: false,
        submenu: true,
        featureKey: "pos",
        submenuItems: [
          { label: "POS 1", link: route.pos, showSubRoute: false, featureKey: "pos" },
          { label: "POS 2", link: route.pos2, showSubRoute: false, featureKey: "pos" },
          { label: "POS Settings", link: "/pos-settings", showSubRoute: false, featureKey: "pos" },
          { label: "POS 3", link: "/pos-3", showSubRoute: false, featureKey: "pos" },
          { label: "POS 4", link: "/pos-4", showSubRoute: false, featureKey: "pos" },
          { label: "POS 5", link: "/pos-5", showSubRoute: false, featureKey: "pos" },
          {
            label: "POS 6",
            link: "#",
            showSubRoute: false,
            external: true,
            featureKey: "pos",
          },
          {
            label: "POS 7",
            link: "#",
            showSubRoute: false,
            external: true,
            featureKey: "pos",
          },
        ],
      },
    ],
  },
  {
    label: "Promo",
    submenuOpen: true,
    submenuHdr: "Promo",
    showSubRoute: false,
    roles: ["owner"],
    submenuItems: [
      {
        label: "Coupons",
        link: "/coupons",
        icon: "ticket",
        showSubRoute: false,
        submenu: false,
        featureKey: "coupons",
      },
      {
        label: "Gift Cards",
        link: route.GiftCard,
        icon: "cards",
        showSubRoute: false,
        submenu: false,
        featureKey: "gift_cards",
      },
      {
        label: "Discount",
        icon: "file-percent",
        showSubRoute: false,
        submenu: true,
        featureKey: "discounts",
        submenuItems: [
          {
            label: "Discount Plan",
            link: route.discountPlan,
            showSubRoute: false,
            featureKey: "discounts",
          },
          { label: "Discount", link: route.discount, showSubRoute: false, featureKey: "discounts" },
        ],
      },
    ],
  },
  {
    label: "Purchases",
    submenuOpen: true,
    submenuHdr: "Purchases",
    showSubRoute: false,
    roles: ["owner"],
    submenuItems: [
      {
        label: "Purchases",
        link: "/purchase-list",
        icon: "shopping-bag",
        showSubRoute: false,
        submenu: false,
        featureKey: "purchases",
      },
      {
        label: "Purchase Order",
        link: "/purchase-order-report",
        icon: "file-unknown",
        showSubRoute: false,
        submenu: false,
        featureKey: "purchase_orders",
      },
      {
        label: "Purchase Return",
        link: "/purchase-returns",
        icon: "file-upload",
        showSubRoute: false,
        submenu: false,
        featureKey: "purchase_returns",
      },
    ],
  },

  {
    label: "Finance & Accounts",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "Finance & Accounts",
    roles: ["owner"],
    submenuItems: [
      {
        label: "Expenses",
        submenu: true,
        showSubRoute: false,
        icon: "file-stack",
        featureKey: "expenses",
        submenuItems: [
          { label: "Expenses", link: "/expense-list", showSubRoute: false, featureKey: "expenses" },
          {
            label: "Expense Category",
            link: "/expense-category",
            showSubRoute: false,
            featureKey: "expenses",
          },
        ],
      },
      {
        label: "Income",
        submenu: true,
        showSubRoute: false,
        icon: "file-pencil",
        featureKey: "income",
        submenuItems: [
          { label: "Income", link: "/income", showSubRoute: false, featureKey: "income" },
          {
            label: "Income Category",
            link: "/income-category",
            showSubRoute: false,
            featureKey: "income",
          },
        ],
      },
      {
        label: "Bank Accounts",
        link: route.accountlist,
        icon: "building-bank",
        showSubRoute: false,
        submenu: false,
        featureKey: "bank_accounts",
      },
      {
        label: "Money Transfer",
        link: "/money-transfer",
        icon: "moneybag",
        showSubRoute: false,
        submenu: false,
        featureKey: "money_transfer",
      },
      {
        label: "Balance Sheet",
        link: "/balance-sheet",
        icon: "report-money",
        showSubRoute: false,
        submenu: false,
        featureKey: "balance_sheet",
      },
      {
        label: "Trial Balance",
        link: "/trial-balance",
        icon: "alert-circle",
        showSubRoute: false,
        submenu: false,
        featureKey: "trial_balance",
      },
      {
        label: "Cash Flow",
        link: "/cash-flow",
        icon: "zoom-money",
        showSubRoute: false,
        submenu: false,
        featureKey: "cash_flow",
      },
      {
        label: "Account Statement",
        link: "/account-statement",
        icon: "file-infinity",
        showSubRoute: false,
        submenu: false,
        featureKey: "account_statement",
      },
    ],
  },

  {
    label: "People",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "People",
    roles: ["owner", "manager"],
    submenuItems: [
      {
        label: "Customers",
        link: route.customers,
        icon: "users-group",
        showSubRoute: false,
        submenu: false,
        featureKey: "customers",
      },
      {
        label: "Billers",
        link: "/billers",
        icon: "user-up",
        showSubRoute: false,
        submenu: false,
        featureKey: "billers",
      },
      {
        label: "Suppliers",
        link: "/suppliers",
        icon: "user-dollar",
        showSubRoute: false,
        submenu: false,
        featureKey: "suppliers",
      },
      {
        label: "Branches",
        link: "/branch-list",
        icon: "home-bolt",
        showSubRoute: false,
        submenu: false,
        featureKey: "branches",
      },
      {
        label: "Warehouses",
        link: "/warehouse",
        icon: "archive",
        showSubRoute: false,
        submenu: false,
        featureKey: "warehouses",
      },
    ],
  },

  {
    label: "HRM",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "HRM",
    roles: ["owner", "manager"],
    submenuItems: [
      {
        label: "Employees",
        link: "/employees-grid",
        icon: "user",
        showSubRoute: false,
        featureKey: "employees",
      },
      {
        label: "Departments",
        link: "/department-grid",
        icon: "compass",
        showSubRoute: false,
        featureKey: "departments",
      },
      {
        label: "Designations",
        link: "/designation",
        icon: "git-merge",
        showSubRoute: false,
        featureKey: "designations",
      },
      {
        label: "Shifts",
        link: "/shift",
        icon: "arrows-shuffle",
        showSubRoute: false,
        featureKey: "shifts",
      },

      {
        label: "Attendance",
        link: "#",
        icon: "user-cog",
        showSubRoute: false,
        submenu: true,
        featureKey: "attendance",

        submenuItems: [
          { label: "Employee", link: "/attendance-employee", featureKey: "attendance" },
          { label: "Admin", link: "/attendance-admin", featureKey: "attendance" },
        ],
      },
      {
        label: "Leaves",
        link: "#",
        icon: "calendar",
        showSubRoute: false,
        submenu: true,
        featureKey: "leaves",
        submenuItems: [
          { label: "Employee Leaves", link: "/leaves-employee", featureKey: "leaves" },
          { label: "Admin Leaves", link: "/leaves-admin", featureKey: "leaves" },
          { label: "Leave Types", link: "/leave-types", featureKey: "leaves" },
        ],
      },
      {
        label: "Holidays",
        link: "/holidays",
        icon: "calendar-share",
        showSubRoute: false,
        featureKey: "holidays",
      },

      {
        label: "Payroll",
        link: "#",
        icon: "file-dollar",
        showSubRoute: false,
        submenu: true,
        featureKey: "payroll",
        submenuItems: [
          { label: "Employee Salary", link: route.payrollList, featureKey: "payroll" },
          { label: "Payslip", link: "/payslip", featureKey: "payroll" },
        ],
      },
    ],
  },
  {
    label: "Reports",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "Reports",
    roles: ["owner", "manager"],
    submenuItems: [
      {
        label: "Sales Report",
        icon: "chart-bar",
        showSubRoute: false,
        submenu: true,
        featureKey: "sales_report",
        submenuItems: [
          { label: "Sales Report", link: "/sales-report", featureKey: "sales_report" },
          { label: "Best Seller", link: "/best-seller", featureKey: "sales_report" },
        ],
      },
      {
        label: "Purchase Report",
        link: "/purchase-report",
        icon: "chart-pie-2",
        showSubRoute: false,
        featureKey: "purchase_report",
      },
      {
        label: "Inventory Report",
        icon: "triangle-inverted",
        showSubRoute: false,
        submenu: true,
        featureKey: "inventory_report",
        submenuItems: [
          { label: "Inventory Report", link: "/inventory-report", featureKey: "inventory_report" },
          { label: "Stock History", link: "/stock-history", featureKey: "inventory_report" },
          { label: "Sold Stock", link: "/sold-stock", featureKey: "inventory_report" },
        ],
      },
      {
        label: "Invoice Report",
        link: route.invoicereportnew,
        icon: "businessplan",
        showSubRoute: false,
        featureKey: "invoice_report",
      },
      {
        label: "Supplier Report",
        icon: "user-star",
        showSubRoute: false,
        submenu: true,
        featureKey: "supplier_report",
        submenuItems: [
          { label: "Supplier Report", link: "/supplier-report", featureKey: "supplier_report" },
          { label: "Supplier Due Report", link: "/supplier-due-report", featureKey: "supplier_report" },
        ],
      },
      {
        label: "Customer Report",

        icon: "report",
        showSubRoute: false,
        submenu: true,
        featureKey: "customer_report",
        submenuItems: [
          { label: "Customer Report", link: "/customer-report", featureKey: "customer_report" },
          { label: "Customer Due Report", link: "/customer-due-report", featureKey: "customer_report" },
        ],
      },
      {
        label: "Product Report",
        icon: "report-analytics",
        showSubRoute: false,
        submenu: true,
        featureKey: "product_report",
        submenuItems: [
          { label: "Product Report", link: "/product-report", featureKey: "product_report" },
          { label: "Product Expiry Report", link: "/product-expiry-report", featureKey: "product_report" },
          {
            label: "Product Quantity Alert",
            link: route.productquantityreport,
            featureKey: "product_report",
          },
        ],
      },
      {
        label: "Expense Report",
        link: "/expense-report",
        icon: "file-vector",
        showSubRoute: false,
        featureKey: "expense_report",
      },
      {
        label: "Income Report",
        link: "/income-report",
        icon: "chart-ppf",
        showSubRoute: false,
        featureKey: "income_report",
      },
      {
        label: "Tax Report",
        link: "/tax-report",
        icon: "chart-dots-2",
        showSubRoute: false,
        featureKey: "tax_report",
      },
      {
        label: "Profit & Loss",
        link: "/profit-loss-report",
        icon: "chart-donut",
        showSubRoute: false,
        featureKey: "profit_loss",
      },
      {
        label: "Annual Report",
        link: "/annual-report",
        icon: "report-search",
        showSubRoute: false,
        featureKey: "annual_report",
      },
    ],
  },

  {
    label: "Content (CMS)",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "Content (CMS)",
    roles: ["platform"],
    submenuItems: [
      {
        label: "Pages",
        icon: "page-break",
        showSubRoute: false,
        submenu: true,
        featureKey: "platform.pages",
        submenuItems: [{ label: "Pages", link: "/pages", featureKey: "platform.pages" }],
      },
      {
        label: "Blog",
        icon: "wallpaper",
        showSubRoute: false,
        submenu: true,
        featureKey: "platform.blogs",
        submenuItems: [
          { label: "All Blog", link: all_routes.allBlogs, featureKey: "platform.blogs" },
          { label: "Blog Tags", link: all_routes.blogTag, featureKey: "platform.blogs" },
          { label: "Categories", link: all_routes.blogCategories, featureKey: "platform.blogs" },
          { label: "Blog Comments", link: all_routes.blogComments, featureKey: "platform.blogs" },
        ],
      },
      {
        label: "Location",
        icon: "map-pin",
        showSubRoute: false,
        submenu: true,
        featureKey: "platform.locations",
        submenuItems: [
          { label: "Countries", link: all_routes.countries, featureKey: "platform.locations" },
          { label: "States", link: all_routes.states, featureKey: "platform.locations" },
          { label: "Cities", link: all_routes.cities, featureKey: "platform.locations" },
        ],
      },
      {
        label: "Testimonials",
        icon: "star",
        link: all_routes.testimonial,
        showSubRoute: false,
        submenu: false,
        featureKey: "platform.testimonials",
      },
      {
        label: "FAQ",
        icon: "help-circle",
        link: all_routes.faq,
        showSubRoute: false,
        submenu: false,
        featureKey: "platform.faq",
      },
    ],
  },
  {
    label: "User Management",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "User Management",
    roles: ["owner"],
    submenuItems: [
      {
        label: "Users",
        link: "/users",
        icon: "shield-up",
        showSubRoute: false,
        featureKey: "users",
      },
      {
        label: "Roles & Permissions",
        link: "/roles-permissions",
        icon: "jump-rope",
        showSubRoute: false,
        featureKey: "permissions",
      },
      {
        label: "Delete Account Request",
        link: "/delete-account",
        icon: "trash-x",
        showSubRoute: false,
        featureKey: "user_management",
      },
    ],
  },
  {
    label: "Pages",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "Pages",
    roles: ["owner"],
    submenuItems: [
      {
        label: "Profile",
        link: "/profile",
        icon: "user-circle",
        showSubRoute: false,
      },
      {
        label: "Authentication",
        submenu: true,
        showSubRoute: false,
        icon: "shield",
        submenuItems: [
          {
            label: "Login",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              { label: "Cover", link: "/signin", showSubRoute: false },
              { label: "Illustration", link: "/signin-2", showSubRoute: false },
              { label: "Basic", link: "/signin-3", showSubRoute: false },
            ],
          },
          {
            label: "Register",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              { label: "Cover", link: "/register", showSubRoute: false },
              {
                label: "Illustration",
                link: "/register-2",
                showSubRoute: false,
              },
              { label: "Basic", link: "/register-3", showSubRoute: false },
            ],
          },
          {
            label: "Forgot Password",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              { label: "Cover", link: "/forgot-password", showSubRoute: false },
              {
                label: "Illustration",
                link: "/forgot-password-2",
                showSubRoute: false,
              },
              {
                label: "Basic",
                link: "/forgot-password-3",
                showSubRoute: false,
              },
            ],
          },
          {
            label: "Reset Password",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              { label: "Cover", link: "/reset-password", showSubRoute: false },
              {
                label: "Illustration",
                link: "/reset-password-2",
                showSubRoute: false,
              },
              {
                label: "Basic",
                link: "/reset-password-3",
                showSubRoute: false,
              },
            ],
          },
          {
            label: "Email Verification",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              {
                label: "Cover",
                link: "/email-verification",
                showSubRoute: false,
              },
              {
                label: "Illustration",
                link: "/email-verification-2",
                showSubRoute: false,
              },
              {
                label: "Basic",
                link: "/email-verification-3",
                showSubRoute: false,
              },
            ],
          },
          {
            label: "2 Step Verification",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              {
                label: "Cover",
                link: "/two-step-verification",
                showSubRoute: false,
              },
              {
                label: "Illustration",
                link: "/two-step-verification-2",
                showSubRoute: false,
              },
              {
                label: "Basic",
                link: "/two-step-verification-3",
                showSubRoute: false,
              },
            ],
          },
          { label: "Lock Screen", link: "/lock-screen", showSubRoute: false },
        ],
      },
      {
        label: "Error Pages",
        submenu: true,
        showSubRoute: false,
        icon: "file-x",
        submenuItems: [
          { label: "404 Error", link: "/error-404", showSubRoute: false },
          { label: "500 Error", link: "/error-500", showSubRoute: false },
        ],
      },

      {
        label: "Blank Page",
        link: "/blank-page",
        icon: "file",
        showSubRoute: false,
      },
      {
        label: "Pricing",
        link: route.pricing,
        icon: "currency-dollar",
        showSubRoute: false,
      },
      {
        label: "Coming Soon",
        link: "/coming-soon",
        icon: "send",
        showSubRoute: false,
      },
      {
        label: "Under Maintenance",
        link: "/under-maintenance",
        icon: "alert-triangle",
        showSubRoute: false,
      },
    ],
  },
  {
    label: "Billing",
    link: "/billing",
    icon: "credit-card",
    showSubRoute: false,
    roles: ["owner", "manager"],
    featureKey: "billing",
  },
  {
    label: "Settings",
    submenu: true,
    showSubRoute: false,
    submenuHdr: "Settings",
    roles: ["owner"],
    submenuItems: [
      {
        label: "General Settings",
        submenu: true,
        showSubRoute: false,
        icon: "settings",
        featureKey: "general_settings",
        submenuItems: [
          { label: "Profile", link: "/general-settings", featureKey: "general_settings" },
          { label: "Security", link: "/security-settings", featureKey: "general_settings" },
          { label: "Notifications", link: "/notification", featureKey: "general_settings" },
          { label: "Connected Apps", link: "/connected-apps", featureKey: "general_settings" },
        ],
      },
      {
        label: "Website Settings",
        submenu: true,
        showSubRoute: false,
        icon: "world",
        featureKey: "website_settings",
        submenuItems: [
          {
            label: "System Settings",
            link: "/system-settings",
            showSubRoute: false,
            featureKey: "website_settings",
          },
          {
            label: "Company Settings",
            link: "/company-settings",
            showSubRoute: false,
            featureKey: "website_settings",
          },
          {
            label: "Localization",
            link: "/localization-settings",
            showSubRoute: false,
            featureKey: "website_settings",
          },
          { label: "Prefixes", link: "/prefixes", showSubRoute: false, featureKey: "website_settings" },
          { label: "Preference", link: "/preference", showSubRoute: false, featureKey: "website_settings" },
          { label: "Appearance", link: "/appearance", showSubRoute: false, featureKey: "website_settings" },
          {
            label: "Social Authentication",
            link: "/social-authentication",
            showSubRoute: false,
            featureKey: "website_settings",
          },
          {
            label: "Language",
            link: "/language-settings",
            showSubRoute: false,
            featureKey: "website_settings",
          },
        ],
      },
      {
        label: "App Settings",
        submenu: true,
        showSubRoute: false,
        icon: "device-mobile",
        featureKey: "app_settings",
        submenuItems: [
          {
            label: "Invoice",
            link: "/invoice-settings",
            showSubRoute: false,
            submenu: true,
            featureKey: "app_settings",
            submenuItems: [
              { label: "Invoice Settings", link: "/invoice-settings", featureKey: "app_settings" },
              { label: "Invoice Template", link: "/invoice-template", featureKey: "app_settings" },
            ],
          },
          { label: "Printer", link: "/printer-settings", showSubRoute: false, featureKey: "app_settings" },
          { label: "POS", link: "/pos-settings", showSubRoute: false, featureKey: "pos" },
          {
            label: "Custom Fields",
            link: "/custom-fields",
            showSubRoute: false,
            featureKey: "app_settings",
          },
        ],
      },
      {
        label: "System Settings",
        submenu: true,
        showSubRoute: false,
        icon: "device-desktop",
        featureKey: "system_settings",
        submenuItems: [
          {
            label: "Email",
            link: "/email-settings",
            showSubRoute: false,
            submenu: true,
            featureKey: "system_settings",
            submenuItems: [
              { label: "Email Settings", link: "/email-settings", featureKey: "system_settings" },
              { label: "Email Template", link: "/email-template", featureKey: "system_settings" },
            ],
          },
          {
            label: "SMS Gateways",
            link: "/sms-gateway",
            showSubRoute: false,
            submenu: true,
            featureKey: "system_settings",
            submenuItems: [
              { label: "SMS Settings", link: "/sms-settings", featureKey: "system_settings" },
              { label: "SMS Template", link: route.smstemplate, featureKey: "system_settings" },
            ],
          },
          { label: "OTP", link: "/otp-settings", showSubRoute: false, featureKey: "system_settings" },
          {
            label: "GDPR Cookies",
            link: "/gdpr-settings",
            showSubRoute: false,
            featureKey: "system_settings",
          },
        ],
      },
      {
        label: "Financial Settings",
        submenu: true,
        showSubRoute: false,
        icon: "settings-dollar",
        featureKey: "financial_settings",
        submenuItems: [
          {
            label: "Payment Gateway",
            link: "/payment-gateway-settings",
            showSubRoute: false,
            featureKey: "financial_settings",
          },
          {
            label: "Bank Accounts",
            link: "/bank-settings-grid",
            showSubRoute: false,
            featureKey: "financial_settings",
          },
          { label: "Tax Rates", link: "/tax-rates", showSubRoute: false, featureKey: "financial_settings" },
          {
            label: "Currencies",
            link: "/currency-settings",
            showSubRoute: false,
            featureKey: "financial_settings",
          },
        ],
      },
      {
        label: "Other Settings",
        submenu: true,
        showSubRoute: false,
        icon: "settings-2",
        featureKey: "general_settings",
        submenuItems: [
          { label: "Storage", link: "/storage-settings", showSubRoute: false, featureKey: "general_settings" },
          {
            label: "Ban IP Address",
            link: "/ban-ip-address",
            showSubRoute: false,
            featureKey: "general_settings",
          },
        ],
      },
      {
        label: "Logout",
        link: "/signin",
        icon: "logout",
        showSubRoute: false,
      },
    ],
  },

  {
    label: "UI Interface",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "UI Interface",
    roles: ["owner"],
    submenuItems: [
      {
        label: "Base UI",
        submenu: true,
        showSubRoute: false,
        icon: "vector-bezier",
        submenuItems: [
          { label: "Alerts", link: "/ui-alerts", showSubRoute: false },
          { label: "Accordion", link: "/ui-accordion", showSubRoute: false },
          { label: "Avatar", link: "/ui-avatar", showSubRoute: false },
          { label: "Badges", link: "/ui-badges", showSubRoute: false },

          { label: "Buttons", link: "/ui-buttons", showSubRoute: false },
          {
            label: "Button Group",
            link: "/ui-buttons-group",
            showSubRoute: false,
          },
          { label: "Breadcrumb", link: "/ui-breadcrumb", showSubRoute: false },
          { label: "Card", link: "/ui-cards", showSubRoute: false },
          { label: "Carousel", link: "/ui-carousel", showSubRoute: false },

          { label: "Dropdowns", link: "/ui-dropdowns", showSubRoute: false },
          { label: "Grid", link: "/ui-grid", showSubRoute: false },
          { label: "Images", link: "/ui-images", showSubRoute: false },
          { label: "Links", link: "/ui-links", showSubRoute: false },
          { label: "List Group", link: "/ui-list-group", showSubRoute: false },
          { label: "Modals", link: "/ui-modals", showSubRoute: false },
          { label: "Offcanvas", link: "/ui-offcanvas", showSubRoute: false },
          { label: "Pagination", link: "/ui-pagination", showSubRoute: false },

          { label: "Progress", link: "/ui-progress", showSubRoute: false },
          {
            label: "Placeholders",
            link: "/ui-placeholders",
            showSubRoute: false,
          },

          { label: "Spinner", link: "/ui-spinner", showSubRoute: false },

          { label: "Tabs", link: "/ui-nav-tabs", showSubRoute: false },

          { label: "Tooltips", link: "/ui-tooltips", showSubRoute: false },
          { label: "Typography", link: "/ui-typography", showSubRoute: false },
        ],
      },
      {
        label: "Advanced UI",
        submenu: true,
        showSubRoute: false,
        icon: "stack-forward",
        submenuItems: [
          { label: "Clipboard", link: "/ui-clipboard", showSubRoute: false },
          { label: "Drag & Drop", link: "/ui-drag-drop", showSubRoute: false },

          { label: "Scrollbar", link: "/ui-scrollbar", showSubRoute: false },

          { label: "Lightbox", link: "/ui-lightbox", showSubRoute: false },
        ],
      },
      {
        label: "Charts",
        submenu: true,
        showSubRoute: false,
        icon: "chart-infographic",
        submenuItems: [
          { label: "Apex Charts", link: "/chart-apex", showSubRoute: false },
          { label: "Chart Js", link: "/chart-js", showSubRoute: false },
        ],
      },
      {
        label: "Icons",
        submenu: true,
        showSubRoute: false,
        icon: "icons",
        submenuItems: [
          {
            label: "Fontawesome Icons",
            link: "/icon-fontawesome",
            showSubRoute: false,
          },
          {
            label: "Remix Icon",
            link: "/remix-icon",
            showSubRoute: false,
          },
          {
            label: "Bootstrap Icon",
            link: "/bootstrap-icon",
            showSubRoute: false,
          },
          {
            label: "Tabler Icon",
            link: "/tabler-icon",
            showSubRoute: false,
          },

          {
            label: "Material Icons",
            link: "/icon-material",
            showSubRoute: false,
          },
          { label: "Pe7 Icons", link: "/icon-pe7", showSubRoute: false },

          {
            label: "Themify Icons",
            link: "/icon-themify",
            showSubRoute: false,
          },
          {
            label: "Typicon Icons",
            link: "/icon-typicon",
            showSubRoute: false,
          },
          {
            label: "Bootstrap Icons",
            link: "/icon-bootstrap",
            showSubRoute: false,
          },
          { label: "Flag Icons", link: "/icon-flag", showSubRoute: false },
        ],
      },
      {
        label: "Forms",
        submenu: true,
        showSubRoute: false,
        icon: "input-search",
        submenuItems: [
          {
            label: "Form Elements",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              {
                label: "Basic Inputs",
                link: "/form-basic-inputs",
                showSubRoute: false,
              },
              {
                label: "Checkbox & Radios",
                link: "/form-checkbox-radios",
                showSubRoute: false,
              },
              {
                label: "Input Groups",
                link: "/form-input-groups",
                showSubRoute: false,
              },
              {
                label: "Grid & Gutters",
                link: "/form-grid-gutters",
                showSubRoute: false,
              },
              {
                label: "Form Select",
                link: "/form-select",
                showSubRoute: false,
              },

              {
                label: "File Uploads",
                link: "/form-fileupload",
                showSubRoute: false,
              },
            ],
          },
          {
            label: "Layouts",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              { label: "Horizontal Form", link: "/form-horizontal" },
              { label: "Vertical Form", link: "/form-vertical" },
              { label: "Floating Labels", link: "/form-floating-labels" },
            ],
          },
          { label: "Form Validation", link: "/form-validation" },
          { label: "Select", link: "/form-select2" },
          { label: "Form Wizard", link: "/form-wizard" },
          { label: "Form Picker", link: "/form-picker" },
        ],
      },
      {
        label: "Tables",
        submenu: true,
        showSubRoute: false,
        icon: "table",
        submenuItems: [
          { label: "Basic Tables", link: "/tables-basic" },
          { label: "Data Table", link: "/data-tables" },
        ],
      },
    ],
  },
  {
    label: "Help",
    submenuOpen: true,
    showSubRoute: false,
    submenuHdr: "Help",
    roles: ["platform", "owner", "manager"],
    submenuItems: [
      {
        label: "Documentation",
        link: "#",
        icon: "file-text",
        showSubRoute: false,
      },
      {
        label: "Changelog v2.2.7",
        link: "#",
        icon: "exchange",
        showSubRoute: false,
      },
      {
        label: "Multi Level",
        showSubRoute: false,
        submenu: true,
        icon: "menu-2",
        submenuItems: [
          { label: "Level 1.1", link: "#", showSubRoute: false },
          {
            label: "Level 1.2",
            submenu: true,
            showSubRoute: false,
            submenuItems: [
              { label: "Level 2.1", link: "#", showSubRoute: false },
              {
                label: "Level 2.2",
                submenu: true,
                showSubRoute: false,
                submenuItems: [
                  { label: "Level 3.1", link: "#", showSubRoute: false },
                  { label: "Level 3.2", link: "#", showSubRoute: false },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
